export const CURRENT_TIME_SET = 'CURRENT_TIME_SET';
export const STATE_RESET = 'STATE_RESET';
export const EVENT_ADDED = 'EVENT_ADDED';
export const EVENT_RECEIVED = 'EVENT_RECEIVED';
export const EVENTS_RECEIVED = 'EVENTS_RECEIVED';
